title: DFIR Automation
description: "NodeRED / Juptyer Notebook DFIR Automation and Scripting"
author:
  name: "DFIR David Terrey"
  email: "someone@somewebsite.somedomain"
  url: "https://github.com/dterrey"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "DFIR David Terrey"
year : "2024"
